version: 2
jobs:
  build_test_image:
    machine: true
    context: build
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          make push_test_image
  test:
    docker:
      - image: saturncloud/sutils-test
    steps:
      - checkout
      - run: |
          export PATH=/opt/conda/bin:${PATH}
          make test
workflows:
  version: 2
  build_test_image:
    jobs:
      - build_test_image:
          context: build
          filters:
            tags:
              only: /^test-image.*/
            branches:
              ignore: /.*/
  test:
    jobs:
      - test:
          context: build
  