package:
  name: sutils
  version: {{os.environ.get('CIRCLE_TAG').split('-')[-1]}}
build:
  number: 1
  noarch: generic
requirements:
  build:
    - python=3.7
  run:
    - python=3.7

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
